(custom-set-variables
 '(abbrev-mode t)
 '(backward-delete-function 'backward-delete-char-untabify)
 '(browse-url-browser-function 'browse-url-netscape)
 '(case-fold-search t)
 '(column-number-mode t)
 '(compilation-read-command nil)
 '(compilation-window-height 5)
 '(dabbrev-upcase-means-case-search t)
 '(delete-key-deletes-forward t)
 '(font-lock-mode t nil (font-lock))
 '(line-number-mode t)
 '(make-backup-files nil)
 '(matlab-block-verify-max-buffer-size 2000)
 '(matlab-case-level '(0 . 4)
)
 '(matlab-comment-column 120)
 '(matlab-comment-region-s "%%% ")
 '(matlab-eei-breakpoint-marker-colors '("black" . "orange")
)
 '(matlab-eei-key-bindings '(("[f10]" . matlab-eei-step)
  ("[f11]" . matlab-eei-step-in)
  ("[(shift f11)]" . matlab-eei-step-out)
  ("[f5]" . matlab-eei-run-continue)
  ("[f12]" . matlab-eei-breakpoint-set-clear)
  ("[f3]" . matlab-eei-eval-region))
)
 '(matlab-eei-provisional-breakpoint-marker-colors '("red" . "orange red")
)
 '(matlab-fill-count-ellipsis-flag nil)
 '(matlab-fill-fudge-hard-maximum 129)
 '(matlab-handle-simulink nil)
 '(matlab-highlight-block-match-flag t)
 '(matlab-highlight-cross-function-variables t t)
 '(matlab-indent-function-body nil)
 '(matlab-keyword-list '("global" "persistent" "for" "while" "if" "elseif" "else" "endfunction" "return" "break" "continue" "switch" "case" "otherwise" "try" "catch" "tic" "toc" "import" "rethrow")
)
 '(matlab-return-add-semicolon t)
 '(matlab-show-periodic-code-details-flag t)
 '(matlab-verify-on-save-flag t t)
 '(matlab-vers-on-startup nil)
 '(mlint-programs '("/opt/linux/x86_64/matlab/7.4/bin/glnxa64/mlint" "mlint")
)
 '(mlint-scan-for-fixes-flag t)
 '(mode-compile-never-edit-command-p t)
 '(modeline-3d-p t)
 '(next-line-add-newlines nil)
 '(only-global-abbrevs nil)
 '(ps-paper-type 'a4)
 '(ps-print-color-p nil)
 '(query-user-mail-address nil)
; '(require-final-newline 'ask)
 '(speedbar-tag-hierarchy-method nil)
 '(standard-indent 2 t)
 '(toolbar-mail-reader 'pine)
 '(truncate-lines t)
 '(user-mail-address "crpi@imc.nl")
 '(xslt-process-java-program "java-1.4.0")
 '(xslt-process-pdf-viewer '(acroread)
))
(custom-set-faces
 '(default ((t (:stipple nil :background "#000000" :foreground "#ffffff" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 96 :width normal :family "b&h lucidatypewriter"))) t)
 '(custom-comment-tag-face ((((class color) (background light)) (:foreground "#55aaff"))))
 '(custom-group-tag-face ((((class color) (background light)) (:foreground "yellow" :underline t))))
 '(custom-variable-tag-face ((((class color) (background light)) (:foreground "yellow" :underline t))))
 '(diff-added-face ((t (:foreground "white"))))
 '(diff-changed-face ((t (:foreground "cyan"))))
 '(diff-file-header-face ((((class color) (background light)) (:foreground "yellow" :bold t))))
 '(diff-header-face ((((class color) (background light)) (:foreground "yellow"))))
 '(diff-hunk-header-face ((((class color) (background light)) (:background "red"))))
 '(diff-index-face ((((class color) (background light)) (:foreground "yellow" :bold t))))
 '(diff-removed-face ((t (:foreground "cyan"))))
 '(font-latex-math-face ((((class color) (background light)) (:foreground "SandyBrown"))))
 '(font-latex-title-1-face ((((class color) (background light)) (:foreground "DeepPink" :bold t))))
 '(font-latex-title-2-face ((((class color) (background light)) (:foreground "DeePpink" :bold t))))
 '(font-latex-title-3-face ((((class color) (background light)) (:foreground "DeePpink" :bold t))))
 '(font-latex-title-4-face ((((class color) (background light)) (:foreground "DeepPink" :bold t))))
 '(font-latex-verbatim-face ((((class color) (background light)) (:foreground "SandyBrown" :family "courier"))))
 '(font-lock-builtin-face ((((class color) (background light)) (:foreground "#afff00"))))
 '(font-lock-comment-face ((((class color) (background light)) (:foreground "#ffff00"))))
 '(font-lock-constant-face ((((class color) (background light)) (:foreground "#feabab"))))
 '(font-lock-doc-string-face ((((class color) (background light)) (:foreground "#00ff00"))))
 '(font-lock-function-name-face ((((class color) (background light)) (:foreground "#ff0000"))))
 '(font-lock-keyword-face ((((class color) (background light)) (:foreground "#74f7ff"))))
 '(font-lock-preprocessor-face ((((class color) (background light)) (:foreground "green2"))))
 '(font-lock-reference-face ((((class color) (background light)) (:foreground "#00ffff"))))
 '(font-lock-string-face ((((class color) (background light)) (:foreground "#fd62fd"))))
 '(font-lock-type-face ((((class color) (background light)) (:foreground "steelblue1"))))
 '(font-lock-variable-name-face ((((class color) (background light)) (:foreground "#74ff77"))))
 '(jde-java-font-lock-api-face ((((class color) (background light)) (:foreground "#ffb620"))))
 '(jde-java-font-lock-doc-tag-face ((((class color) (background light)) (:foreground "green3"))))
 '(jde-java-font-lock-link-face ((t (:foreground "#fa66ff" :italic nil :underline t))))
 '(jde-java-font-lock-modifier-face ((((class color) (background light)) (:foreground "#c0fd0a"))))
 '(jde-java-font-lock-operator-face ((((class color)) (:foreground "light blue"))))
 '(jde-java-font-lock-package-face ((((class color) (background light)) (:foreground "green"))))
 '(linemark-funny-face ((((class color) (background light)) (:foreground "black" :background "cyan" :bold t))))
 '(linemark-go-face ((((class color) (background light)) (:foreground "black" :background "#ddd88d" :bold t)))))
