#
# Files from '.ssh' directory
#

#
# Files from 'CRON' directory
#

#
# Files from the 'bin' directory
#
bin/attachToContainer.sh $HOME/bin/attachToContainer.sh
bin/sshToMinion.sh $HOME/bin/sshToMinion.sh

# Git files
.gitignore_global $HOME/.gitignore_global
.gitconfig $HOME/.gitconfig
#
# Kubernetes config dir
#
.kube $HOME/.kube

#
# Atom stuf
#
atom.apiblueprint.cson $HOME/.atom/packages/language-api-blueprint/grammars/apiblueprint.cson
