#!/bin/bash


source ~/.bashrc

# Enable alias expansion
shopt -s expand_aliases

UpdateProject()
{
    local myModule='algocore'
    local myBranch=$1

    # Set the active project
    sam $myModule $myBranch

    # Update it
    sud  $ACTIVE_MODULE $ACTIVE_BRANCH --non-interactive

    # Go to the source directory
    cd $SOURCE_DIR

    # Create the user directory, if it doesn't exist already
    local myUserDir='.user/dailyDiffs'
    if [ ! -d "$myUserDir" ]
    then
	mkdir -p "$myUserDir"
    fi

    local myToday=`date -d tomorrow +%Y-%m-%d`
    local myYesterday=`date -d yesterday +%Y-%m-%d`
    local myFile="svn.$myToday"
    svn diff -r{$myYesterday}:{$myToday} > ${myUserDir}/${myFile}.diff
    svn log -r{$myYesterday}:{$myToday} > ${myUserDir}/${myFile}.log

    ln -s -f ${myFile}.diff ${myUserDir}/latest.diff
    ln -s -f ${myFile}.log ${myUserDir}/latest.log
}


# This should work only on the laptop
if [ `hostname` != "crpinotebook.trading.imc.intra" ]
then
    exit 0
fi

myInterestingProjects='impl_sagcor239 impl_sagcor243 res_trend_following'

for p in $myInterestingProjects
do
    UpdateProject $p
    echo "=============================="
    echo "Updated project: $p"
    echo "=============================="
done