#!/bin/bash

##
# Here you can overwrite the MATLAB_STABLE_BRANCH variable
##
MATLAB_STABLE_BRANCH="$HOME/code/felix_for_export"


cd $MATLAB_STABLE_BRANCH
svn update

LOG_DIR=".user/log/java_optimizer"
LOG_FILE="exportToOptimizerDb.`date +%d.%m.%Y.log`"

#GREP_RESULT=`grep sag_opt_ferrari Registry.conf | grep localhost`
#if [ -z "${GREP_RESULT}" ]; then
#    echo "The sag_opt_ferrari database is not on localhost in the Registry file"
#    exit 0
#fi

# Check if log directory exists
if [ ! -d $LOG_DIR ]; then
    mkdir -p $LOG_DIR
fi


# Note: when passing a function call using '-r', there must be no spaces between the arguments of the function (only commas), otherwise
# this will produce an error message from the Matlab function 'eval', which is used internally to run the function. Something like:
# eval: line 1: syntax error near unexpected token `)'
matlab.5 -nodisplay -r "try,ExportToOptimizerDB();catch,end;quit" -logfile $LOG_DIR/$LOG_FILE

